name: Build and Push Auth Server Image

on:
  push:
    tags:
      - 'auth-server-v*.*.*'

jobs:
  build-push:
    name: Push Docker image to Tencent Docker Registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Login to Tencent CCR
        uses: docker/login-action@v2
        with:
          registry: ccr.ccs.tencentyun.com
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract Semantic Version
        id: version
        run: |
          # 提取纯净语义版本 (e.g. v1.2.3)
          VERSION="${GITHUB_REF#refs/tags/auth-server-}"
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: ./auth_server
          push: true
          tags: |
            ccr.ccs.tencentyun.com/sphinx/traceable-auth-server:${{ steps.version.outputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
